const videos=[
  {title:"Warehouse map",
   src:'//videos.sproutvideo.com/embed/709adbb01d1ae4c2f8/a83ba8f0ee45dbea',
   videoDesc:'”Having a full visual of the inventory in our warehouse through this mapping software has improved our flow tenfold.”',
   name:'John Malfitana, General Manager',
   place:'Warehouse and Distribution Solutions',
   pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyWarehouseMap.pdf',
  },
  {title:"Quotes using a cloud database",
   src:'//videos.sproutvideo.com/embed/e89adbb31918e2cf60/7f694f9c519d3f83',
   videoDesc:'“The tool has automated a manual process that took 15 minutes to complete, but which now takes 2.5 to 5 minutes.” ',
   name:'Rick Mansley, Director',
   place:'Alrick Healthcare',
   pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyQuotesCloud.pdf',
  },

  {title:"Hospital ward management",
   src:'http://ableowl.net/wp-content/uploads/2017/07/HospitalWardManagementWebPageImage.png',
   videoDesc:'“The application has been in use for 3 years and has run smoothly the whole time.”',
   name:'Susan Jadkonis, Finance Manager',
   place:'Toowong Private Hospital',
   pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyHospitalWardManagement.pdf',
  },

  {title:"CRM",
   src:'http://ableowl.net/wp-content/uploads/2017/07/CRMWebPageImage.png',
   videoDesc:'',
   name:'',
   place:'',
  pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyCRM.pdf',
  },

  {title:"RAPID SALES QUOTES",
   src:'//videos.sproutvideo.com/embed/e89adbb11d1fe7cb60/770d8a46981b0400',
   videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy."',
   name:'Gordon Foss, Finance Director',
   place:'Crown fork lifts',
   pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyQuotes.pdf',

},

{title:"Bill of Materials from external inputs",
 src:'//videos.sproutvideo.com/embed/4c9adbb11d1fe7c6c4/9700fbd6787bff91',
 videoDesc:'“A task of 25+hours reduced to 90 seconds.”',
 name:'Neville Ward, Research and Development Manager',
 place:'Robertson Manufacturing',
 pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyRobertsonMfng.pdf',
},
{title:"Dairy diary",
 src:'//videos.sproutvideo.com/embed/709adbb11d1fe7c5f8/d75130861ca597db',
 videoDesc:'"The software is easy to pick up, easy to follow, simple and everything is automated."',
 name:'Krispin Kannan, Veterinarian ',
 place:'VetEnt',
  pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyDairyDiary.pdf',
},
{title:"Import MYOB actuals into reports",
 src:'//videos.sproutvideo.com/embed/e89adbb11f16eccb60/a9883e874f34fe7e',
 videoDesc:'',
 name:'',
 place:'Australian Orthopaedic Association, Sydney',
 pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyAccountsImportToReport.pdf',
},


{title:"Rapid course assessment",
 src:'//videos.sproutvideo.com/embed/e89adbb11f16efc860/849a3a94ada228d5',
 place:'RMIT University, Melbourne',
 pdfFileUrl: 'http://ableowl.net/wp-content/uploads/2017/07/CaseStudyRapidCourseAssessment.pdf',
},

/*{title:"Invoicing and sales reporting",
 src:'http://ableowl.net/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'',
 name:'',
 place:'',
},

{title:"Telephone market research survey answers",
 src:'http://ableowl.net/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'',
 name:'',
 place:'',
},
{title:"Logistics planning for shipments, stocks and multiple locations",
 src:'http://ableowl.net/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'',
 name:'',
 place:'',
},
*/
]


export default videos;
