const videos=[
  {title:"RAPID SALES QUOTES",
   img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
   videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
   name:'Gordon Foss, Finance Director.',
   place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
{title:"RAPID SALES QUOTES",
 img:'http://test.nzpuretour.com/wp-content/uploads/2017/07/video-img.png',
 videoDesc:'"We reduced the task from most of a day to 10 minutes and greatly improved accuracy"',
 name:'Gordon Foss, Finance Director.',
 place:'Crown fork lifts, New Zealand',
},
]


export default videos;
